spring:
  application:
    name: Reg and auth example (DEV)
    copyright:
      name: Moya firma
      year-start: 2010
      year-stop: 2022
      designed-by: Radius17
    registration:
      disabled: false
    notifications:
      logging:
        level: debug
      keys:
        public: ${REG_AUTH_PUBLIC_KEY_FOR_NOTIFICATIONS:ENV_VAR_NEEDED}
        private: ${REG_AUTH_PRIVATE_KEY_FOR_NOTIFICATIONS:ENV_VAR_NEEDED}
  mail:
    host: ${MAILER_SMTP_HOST:ENV_VAR_NEEDED}
    port: ${MAILER_SMTP_PORT:ENV_VAR_NEEDED}
    username: ${MAILER_SMTP_USERNAME:ENV_VAR_NEEDED}
    password: ${MAILER_SMTP_PASSWORD:ENV_VAR_NEEDED}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          timeout: 2000
    from:
      email: ${MAILER_SMTP_FROM_EMAIL:ENV_VAR_NEEDED}
      name: RegAuth
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${APP_POSTGRES_HOST:localhost}:${APP_POSTGRES_PORT:5432}/${APP_POSTGRES_DB:reg_auth}
    username: ${APP_POSTGRES_USER:postgres}
    password: ${APP_POSTGRES_PWD:1}
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  thymeleaf:
    cache: false
  main:
    allow-circular-references: true
logging:
  level:
    org:
      springframework:
        security: warn
    com: warn
    web: warn
server:
  ssl:
    key-store-type: pkcs12
    key-store: ${REG_AUTH_PKCS12_PATH:classpath:ssl/springboot.p12}
    key-store-password: 1234567
    key-alias: springboot
    enabled: true
  servlet:
    session:
      timeout: 720m
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
    include-binding-errors: always
