spring:
  application:
    name: Reg and auth example
    registration:
      disabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my_database
    username: postgres
    password: 1
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  thymeleaf:
    cache: false
  main:
    allow-circular-references: true
logging:
  level:
    org:
      springframework: info
    com: info
    web: debug
server:
  servlet:
    session:
      timeout: 720m
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
    include-binding-errors: always
